### ISSUE TITLE
Products List Page

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#11]
@thomasjbradley On my products list page, my cards aren't aligned on some screen sizes. I know I had this issue last semester and I used `unit-content-distribute`. Although, with the patterns, I'm not sure how I'd use it. 

I tried putting the `unit-content-distribute` class on the unit in the `products.html` then the other tags like `content-fill` and `content-shrink` on the heading and button in the` product-card.html `but it didn't work. I assume it doesn't work because they're in two separate html files but I don't know how to put the `content-fill` and `content-shrink` in the `products.html`. Do you know how I could make it work? 

<img width="447" alt="Screen Shot 2020-03-25 at 6 09 08 PM" src="https://user-images.githubusercontent.com/43151021/77590778-e900a380-6ec4-11ea-8ba8-e2f78e00bf2e.png">

**Comment by thomasjbradley** [comment]
You’ll have to put `.unit-content-distribute` into the pattern itself, here:
https://github.com/hend0298/ecommerce-pattern-library/blob/master/_patterns/cards/product-card.html#L1

Then add the `.content-fill` class on the `<p>` tag, I think:
https://github.com/hend0298/ecommerce-pattern-library/blob/master/_patterns/cards/product-card.html#L4

**Comment by hend0298** [comment]
@thomasjbradley Okay I did that and it still doesn't work. Does the unit class need to be on the pattern itself or stay on the `products.html` page?

**Comment by thomasjbradley** [comment]
Try adding `.unit-content-distribute` onto the `.unit` & `.content-fill` onto the card `<div>` also.
