### ISSUE TITLE
Cart Total

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#16]
@thomasjbradley On the `confirmation.html`, the cart prices are changed using` {{include.price}} ` but the total is the same so the numbers don't add up. Is there a way to fix that or does it not matter?

<img width="296" alt="Screen Shot 2020-04-10 at 5 41 11 PM" src="https://user-images.githubusercontent.com/43151021/79024972-7d6c3680-7b52-11ea-9758-d2ce0f7a76b3.png">

**Comment by thomasjbradley** [comment]
You’ll need more than one placeholder. You’ll need `{{include.shipping}}` & `{{include.total}}`, etc.
