### ISSUE TITLE
Product Cards on Bulk Pricing Page

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#18]
@thomasjbradley Whenever I copy and paste the product card pattern into `bulk-pricing.html`, only the button shows up. For the products list page, I used the data from the `md` product files so now I can't adjust the headings and all that. I don't know if there's a way to fix that or not. Can I somehow choose the image, heading, etc. of the product cards on the bulk pricing page? I hope that makes sense cause I'm not sure how to explain it.

**Comment by thomasjbradley** [comment]
We just need to make a small adjustment to your code, here:
https://github.com/hend0298/ecommerce-pattern-library/blob/master/bulk-pricing.html#L10

```
{% assign product=site.products[2] %}
{% pattern cards/product-card data=product %}
```

Notice the `assign` line, that says, "get product number 2 and put it into a variable named `product`" (Remember that computer counting starts at `0`, so `2` is actually the *third* product.)

On the next line we change to a lowercase `product` to match the variable we created on the line above in `assign`.
