### ISSUE TITLE
Marks for Surprise eCommerce Page 1

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#20]
@thomasjbradley I finished the first surprise ecommerce page. For the most part, my pattern library handled it well. I had enough headings in my `theme.css` so the hierarchy is pretty good. One issue I did run into was the links. I had removed the underline on the `<a>` in `theme.css` because that worked for the rest of my website. Although, for this page I wanted the links to stand out more. My solution was to add the `.h2` class to the `<a>` to make the links pink so they could stand out better. The other issue was the table on the mobile screen. I wanted to make it scrollable but unfortunately I didn't set that up in my `theme.css` so the table doesn't fit too well on the mobile screen. I only had one minor issue that I was able to fix and one slightly bigger one that I couldn't find a solution for. Overall, I think my pattern library could've been a bit better but I think it still handled this page fairly well.

**Comment by thomasjbradley** [comment]
💥
