### ISSUE TITLE
Marks for Surprise eCommerce Page 2

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#21]
@thomasjbradley I completed the second surprise page! I think my pattern library struggled a bit more with this one. The first issue was the bulk promotion alert. I would've liked to maybe add a light pink background or something to it to make it more noticeable but unfortunately, I didn't think of setting that up in my pattern library. Instead, I just made it an `<h3>` so it was big and pink so that it could at least stand out a bit. I do think it doesn't look too bad though! The only other minor issue I ran into was the styling of the table. Although it does look decent, I feel like it could have more colour or something to make it more noticeable. The banner, product cards and email newsletter sign up worked out well. Overall, I had a few minor issues but I think my pattern library still handled the page pretty well.

**Comment by thomasjbradley** [comment]
👍
