### ISSUE TITLE
Navigation on Safari

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#23]
@thomasjbradley I always look at my website on Chrome but I just checked my website through the Netlify link on Safari and for some reason the icons in my navigation aren't on the same line on Safari. Is there a way to fix this? Are you going to be grading the website using Safari or another browser?

<img width="1680" alt="Screen Shot 2020-04-13 at 12 01 01 PM" src="https://user-images.githubusercontent.com/43151021/79136112-77f33400-7d7e-11ea-9639-320fac542ed5.png">

**Comment by thomasjbradley** [comment]
Before we try to fix anything empty Safari’s cache.

**Comment by hend0298** [comment]
@thomasjbradley Okay I did and it still looks the same

**Comment by hend0298** [comment]
@thomasjbradley Okay I did that and it still looks the same

**Comment by thomasjbradley** [comment]
Get rid of `.list-group-inline` class, here:
https://github.com/hend0298/ecommerce-pattern-library/blob/master/_patterns/header/header.html#L10
