### ISSUE TITLE
Marks for Markdown Manipulator quiz

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#3]
@thomasjbradley I completed the Markdown Manipulator quiz for this week!

<img width="1675" alt="Screen Shot 2020-03-16 at 6 31 30 PM" src="https://user-images.githubusercontent.com/43151021/76805316-deebf000-67b4-11ea-8e1a-f37e0a38eac4.png">

**Comment by thomasjbradley** [comment]
👍
