### ISSUE TITLE
Marks for The leftovers

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#4]
@thomasjbradley For the leftovers assignment from week 9, I completed all my patterns, double checked all my config.yml explanations, made sure the CSS files weren't targeting any HTML elements and made sure each pattern had the appropriate accessibility features. I can just tag you in this issue and you can look at the code right?

**Comment by thomasjbradley** [comment]
Yep—that’s how it works.
I’ve checked the leftovers off.
