### ISSUE TITLE
Marks for YAML Yodeller

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#5]
@thomasjbradley I completed the YAML Yodeller quiz from week 12.

<img width="1679" alt="Screen Shot 2020-03-20 at 4 18 24 PM" src="https://user-images.githubusercontent.com/43151021/77203321-870bfc80-6ac6-11ea-8ada-49792e6d1114.png">

**Comment by thomasjbradley** [comment]
:tada:
