### ISSUE TITLE
Banner on Small Screens

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#6]
@thomasjbradley For my banner on my home page, I have the text placed on top of the image on large screens. Usually on small screens I just make the text on my banner go below the image instead of on top but I want to make it stay on the image. So, how do I make the image size adjust on small screens so the text can still fit on top? For example, like this website I found in the screenshot below.  

<img width="452" alt="Screen Shot 2020-03-22 at 1 02 59 PM" src="https://user-images.githubusercontent.com/43151021/77255400-7b8f1180-6c3d-11ea-804a-9341c7e8c9d5.png">

**Comment by hend0298** [comment]
I know I cropped my image on photoshop to make it the right size though so I might have to fix that to make the image longer for small screens.

**Comment by thomasjbradley** [comment]
I think the best way is to use the `<picture>` tag:
https://learn-the-web.algonquindesign.ca/topics/responsive-retina-images/#picture-element

**Comment by hend0298** [comment]
@thomasjbradley Okay thanks! I tried the `<picture> `tag and it's not working. Do you have any idea why the image won't show up?

**Comment by thomasjbradley** [comment]
The `<img src="">` URLs are not complete:
https://github.com/hend0298/ecommerce-pattern-library/blob/master/_patterns/banner/call-to-action-banner.html#L4-L5

Should be like: `/images/large-banner.jpg`
