### ISSUE TITLE
Question - Product Details 

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#7]
@thomasjbradley For my product-details.html, the code looks like this:

```
<h2 class="push-1-4 h2">Details</h2>
<ul>
  <li>8.25” L × 6.75” W</li>
  <li>Natural white text paper</li>
  <li>August 2019 - December 2020</li>
  <li>Weekly & monthly pages</li>
  <li>Dividers</li>
  <li>Soft Covered spiral-bound</li>
</ul>
```

To add the variables to the list, would I just use {{include.text}} for each` <li>` or would I need to add all the product details to the product's .md file and use the {{include.data}} instead? I hope that makes sense. I'm kinda just overall confused about the difference between using {{include.text}} and the data.

**Comment by thomasjbradley** [comment]
Where will that pattern be used on your website? In the `_layouts/product.html`?

**Comment by hend0298** [comment]
@thomasjbradley It will be on the individual products page

**Comment by hend0298** [comment]
@thomasjbradley Yes it will be on the individual product's page so the `product.html`

**Comment by thomasjbradley** [comment]
I was going to respond but had another question: are the number of `<li>` tags different for each product? Like would you want say 2 `<li>` for one product and 6 `<li>` for another product?

**Comment by hend0298** [comment]
@thomasjbradley Oh yes each product might have more or less `<li>` tags.

**Comment by thomasjbradley** [comment]
Ok, so in the `.md` files you’ll need to create a list, that will be output to the `<li>` tags.

*In the MD, below the info you already have, but above the `---`*
```yml
details:
  - Thing for first li
  - Stuff for second li
  - etc
```

Then, inside that pattern code, you’d change it to look like this:

```html
<ul>
  {% for text in page.details %}
    <li>{{text}}</li>
  {% endfor %}
</ul>
```

**Comment by hend0298** [comment]
@thomasjbradley Okay, thank you! I added that and should this change in the pattern library or did I do it wrong?

<img width="1411" alt="Screen Shot 2020-03-23 at 11 17 49 AM" src="https://user-images.githubusercontent.com/43151021/77332124-016f9300-6cf8-11ea-9bf9-8ca782d20153.png">

**Comment by thomasjbradley** [comment]
Yep, your pattern library will likely go blank. Any errors in terminal?

**Comment by hend0298** [comment]
@thomasjbradley Nope it's all good. Thank you!

**Comment by hend0298** [comment]
@thomasjbradley For some reason most of my products on the products listing page have lost their images and headings. Do you know why that could've happened?
