### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#8]
@thomasjbradley For my main navigation on large screens, I want the text links to be in the centre and the icons to be on the right. I have them like that right now except the text links aren't in the centre. How could I fix that? It's probably an easy fix but for some reason I can't figure it out.

**Comment by thomasjbradley** [comment]
I think it’s that the icons are taking up space—therefore causing the links to be off-centre.

I think, you’d have to remove the icons from the list and instead `position: absolute` them so they don’t take up space in the row.

Or, maybe more easily, use a grid to divide the row, like:

```
1-4    1-2     1-4
```

**Comment by hend0298** [comment]
@thomasjbradley If I use that grid, the logo would be on the same line right?

**Comment by thomasjbradley** [comment]
Um. I dunno. What’s it ideally supposed to look like? Send me a sketch.

**Comment by hend0298** [comment]
@thomasjbradley I want it to look like this.

[desktop-nav-sketch.pdf](https://github.com/hend0298/ecommerce-pattern-library/files/4370546/desktop-nav-sketch.pdf)

It's just you said to use a grid and divide it like:

`1-4 1-2 1-4`

but I only have the text links as a unit and the icons so I can't divide it in three if that makes sense.

**Comment by hend0298** [comment]
@thomasjbradley I want it to look like this.

<img width="663" alt="desktop-nav-sketch" src="https://user-images.githubusercontent.com/43151021/77337815-cffac580-6cff-11ea-8ec5-d1a57d40035a.png">

It's just you said to use a grid and divide it like:

`1-4 1-2 1-4`

but I only have the text links as a unit and the icons as a unit so I can't divide it in three, if that makes sense.

**Comment by thomasjbradley** [comment]
What about this:

```
┌─────────────────────────────┐
│            LOGO             │
├───────┬─────────────┬───────┤
│EMPTY  │  NAV LINKS  │ SOCIAL│
└───────┴─────────────┴───────┘
```

Logo not in the grid, and the nav stuff in a grid below?

**Comment by hend0298** [comment]
@thomasjbradley How do I make an empty unit? Whenever I remove the content from the div with the first unit, it just pushes everything to the left and the nav looks the same as it did before.

**Comment by thomasjbradley** [comment]
Did you keep the unit sizes on the empty unit?

**Comment by hend0298** [comment]
@thomasjbradley Yes I did. I made the empty unit a div. Is that okay or should I use something else?

**Comment by thomasjbradley** [comment]
Yeah, an empty div tag works.

**Comment by hend0298** [comment]
@thomasjbradley It still doesn't take up space on large screens. Do you know why?

**Comment by thomasjbradley** [comment]
There’s an unclosed `<a>` tag, here:
https://github.com/hend0298/ecommerce-pattern-library/blob/master/_patterns/header/header.html#L4
