### ISSUE TITLE
Products listing page issue

### ISSUE THREAD

**Issue by hend0298** [hend0298/ecommerce-pattern-library#9]
@thomasjbradley For some reason most of my products on the products listing page have lost their images and headings. Do you know why that could've happened?

**Comment by thomasjbradley** [comment]
I think it’s because a few of the MD files aren’t indented properly. The `details` key is indented too far.

**Comment by hend0298** [comment]
@thomasjbradley Right, that fixed it. Thank you! I always miss the most obvious mistakes haha
